### ISSUE TITLE
Local branch vs remote branch

### ISSUE THREAD

**Issue by pawamoy** [davisp/ghp-import#113]
I'm using GitHub Pages Import indirectly through MkDocs.

I have two repositories for my docs: one for the sources ([pawamoy/website](https://github.com/pawamoy/website)) and one for the actual publication to GH pages ([pawamoy/pawamoy.github.io](https://github.com/pawamoy/pawamoy.github.io)).

Both repositories use the master branch. So while I'm in `website`, I would like to publish to `pawamoy.github.io`, on its master branch, but not from my local master branch. Instead I'd like to use a different local branch. I'm able to set things up correctly with plain Git:

```bash
# in website repository
git remote add pawamoy.github.io git@github.com:pawamoy/pawamoy.github.io
git fetch pawamoy.github.io
git switch -c publish -t pawamoy.github.io/master
```

However, GHP Import does not make that local/remote distinction, and will either

- copy the built site in the local `publish` branch (:heavy_check_mark:) and push to the remote `publish` branch (:x:)
- copy the built site in the local `master` branch (:x:) and push to the remote `master` branch (:heavy_check_mark:) 

```bash
mkdocs gh-deploy --remote-name pawamoy.github.io --remote-branch publish  # doesn't push on the right branch
mkdocs gh-deploy --remote-name pawamoy.github.io --remote-branch master  # overwrites local master branch
```

Would it make sense to add a "local branch" option to distinguish it from the remote one? To keep things backward compatible, the local branch would use the remote one when not provided. I can try and open a PR for it.

Of course there are alternatives:

1. set up a different branch to build pages from in pawamoy.github.io's GitHub settings
2. merge both repositories into one (pawamoy.github.io). Write sources in master and publish from gh-pages (so needs alternative 1 anyway)

I think I've initially separated it into two repositories to have personal issues in "website" and [Utterances](https://github.com/utterance/utterances) comments in "pawamoy.github.io", though it might not make sense anymore now that we have Discussions and [Giscus](https://github.com/giscus/giscus).

Given it's fairly easy to change the default branch and pages branch on pawamoy.github.io, I'm not sure it is worth it to implement such a feature here. I still feel like it would be nice to let users configure their Git branching themselves (GHP Import would just need to push, without changing the upstream). Any feedback is welcome :slightly_smiling_face:

**Comment by c-w** [comment]
> Would it make sense to add a "local branch" option to distinguish it from the remote one? To keep things backward compatible, the local branch would use the remote one when not provided.

This sounds good to me. A PR would be welcome :raised_hands:

**Comment by pawamoy** [comment]
I tried implementing the change but failed to :joy: 
It seems I don't understand Git, or the code, enough.

IIUC, ghp-import commits the directory into a specific branch, then pushes it with `git push REMOTE BRANCH`. It never checks out the local branch. It seems that if BRANCH there is different than the local branch name, it fails, so I cannot provide a remote branch name. To push to a remote branch which has a different name than the local one, I don't see another way than checking out the local branch, setting it to track the specified remote one, and push. That's more things than what I'm ready to change in the code.

In the meantime I did change my default/pages branch on pawamoy.github.io, so I don't really need this feature anymore. If you feel like it still has value, and if you can provide some guidance, I'm happy to try again, otherwise feel free to close :slightly_smiling_face: 

Thanks for your help and time anyway!

**Comment by c-w** [comment]
Ok, thanks for reporting back!
