### ISSUE TITLE
How to create custom 404 page?

### ISSUE THREAD

**Issue by snowch** [davisp/ghp-import#130]
Is it possible to create a [custom 404](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site) page as part of the workflow with ghp-import?

Thanks!

**Comment by c-w** [comment]
Wouldn't it be sufficient to have your site generation process (so what runs before ghp-import) create a 404.html file at the root which then gets pushed to the branch by ghp-import?

**Comment by snowch** [comment]
Ah, makes sense.  I'll give that a try.

Thanks!

**Comment by snowch** [comment]
If anyone comes across this for jupyterbook, my fix was:

- create 404.html in root of jupyterbook project
- create scripts/custom_extension.py

```
import os
import shutil

def setup(app):
    app.connect('build-finished', copy_404_html)

def copy_404_html(app, exception):
    source_path = "404.html"
    target_path = os.path.join(app.builder.outdir, "404.html")

    if not os.path.exists(source_path):
        print(f"Error: 404.html file not found at {source_path}")
        return

    try:
        shutil.copy(source_path, target_path)
        print("404.html copied successfully to JupyterBook build directory")
    except Exception as e:
        print(f"Error copying 404.html: {e}")
```

- update `_config.yml`

```
sphinx:
  local_extensions:
    custom_extension: scripts/
```
