### ISSUE TITLE
Make it possible to use the tool inside Python

### ISSUE THREAD

**Issue by Kwpolska** [davisp/ghp-import#27]
Hello, and thanks for the awesome tool!

As you have already seen in #26, the Nikola project will use `ghp-import` for its GitHub deploy feature.  There might be one problem though, Python (and thus, ghp-import) is not always in the PATH.  There is a way to change it: instead of installing `ghp-import` into /usr/bin or wherever it is on the system, install the script into `/usr/lib/pythonX.Y/site-packages` (or the usual virtualenv directory, or…) and put a small launcher script in `/usr/bin`.  If `distutils` support is dropped, you can also leverage the usual `entry_points` mechanism and make things easier on Windows users in the process.

I can implement this if you agree.

**Comment by davisp** [comment]
Should be fixed now.
