### ISSUE TITLE
Fails with "Not a git repository"

### ISSUE THREAD

**Issue by acgetchell** [davisp/ghp-import#30]
┌─[adam][Hapkido][~/blog]
└─▪ pelican content -o output -s pelicanconf.py
WARNING: Empty alt attribute for image mimetex.cgi?G_%7B%5Calpha%20%5Cbeta%7D%20=%20T_%7B%5Calpha%20%5Cbeta%7D in /Users/adam/blog/content/new-direction.md
Done: Processed 32 article(s), 0 draft(s) and 0 page(s) in 0.90 seconds.
┌─[adam][Hapkido][~/blog]
└─▪ ghp-import output
Usage: ghp-import [OPTIONS] DIRECTORY

ghp-import: error: Not a git repository (or any of the parent directories): .git

The documentation indicated that the branch is created automatically?

http://docs.getpelican.com/en/3.5.0/tips.html

The output directory is a git repo:

┌─[adam][Hapkido][~/blog]
└─▪ ghp-import output
Usage: ghp-import [OPTIONS] DIRECTORY

ghp-import: error: Not a git repository (or any of the parent directories): .git

┌─[adam][Hapkido][~/blog]
└─▪ cd output
┌─[adam][Hapkido][±][master ✗][~/blog/output]
└─▪ gs
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

```
new file:   Test.html
new file:   archives.html
new file:   are-we-living-in-simulation.html
```

**Comment by dacbarbos** [comment]
I just hit the same issue with: `make github`.  
```
ghp-import: error: Not a git repository (or any of the parent directories): .git
```

**Comment by nflo47** [comment]
what was the solution here ?  i am getting the same error "ghp-import: error: Not a git repository (or any of the parent directories): .git" when running the command from my main directory

**Comment by davisp** [comment]
What does `git status` give you?

**Comment by davisp** [comment]
Closing because its way old.
