### ISSUE TITLE
Timezone calculation logic in ghp-import is incorrect

### ISSUE THREAD

**Issue by lgp171188** [davisp/ghp-import#45]
The logic used is

``` python
currtz = "%+05d" % (-1 * time.timezone / 36) # / 3600 * 100
```

For my timezone IST (+0530), `time.timezone` returns  -19800 which should translate to 5 hours 30 minutes. But the above code calculates it as `+0550`. This sets the timezone incorrectly in the commits created by ghp-import

**Comment by davisp** [comment]
Fixed by cherry-picking your change.

**Comment by RaHorEl** [comment]
❤️❤️🗣️🗣️✊🏿
