### ISSUE TITLE
0.4.3 release?

### ISSUE THREAD

**Issue by matthew-brett** [davisp/ghp-import#51]
Thanks much for ghp-import, I use it a lot.

I found myself trying to build some pages on Windows, and had to update to the latest master to get it to work.  It did work fine from latest master though (ef30cbf). Any chance of a pypi release from latest master for us Windozers?

**Comment by justuswilhelm** [comment]
+1

**Comment by matthew-brett** [comment]
I make a PR for windows support on Python 3.5:  https://github.com/davisp/ghp-import/pull/52

**Comment by davisp** [comment]
0.5.0 is tagged and on pypi.
