### ISSUE TITLE
Please upload 0.4.2 download tarball to PyPI

### ISSUE THREAD

**Issue by farseerfc** [davisp/ghp-import#53]
Hi, I am maintaining `python-ghp-import` package in Arch Linux `[community]` repo.

I found that you have a 0.4.2 release two month ago, and it is released on PyPI.
But [pypi/ghp-import/0.4.2](https://pypi.python.org/pypi/ghp-import/0.4.2) don't have a download file. The latest dowloadable release on PyPI is [pypi/ghp-import/0.4.1](https://pypi.python.org/pypi/ghp-import/0.4.1).

So please upload 0.4.2 tarball to PyPI.
Thank you!

**Comment by d0ugal** [comment]
I suspect this means it was released and then deleted. PyPI wont allow it to be re-uploaded.

**Comment by davisp** [comment]
0.5.0 is tagged and on pypi.
