### ISSUE TITLE
Clobbers custom domain

### ISSUE THREAD

**Issue by allanstreib** [davisp/ghp-import#56]
After publishing, the Github Pages "Custom Domain" repository setting is blanked out.

**Comment by deimosfr** [comment]
Same issue for me

**Comment by deimosfr** [comment]
I've found the issue. It's simply because of the missing CNAME file in the branch. You just have to create one after the build. It would be nice to have a parameter to allow it.

**Comment by allanstreib** [comment]
Thanks, that fixes it.

**Comment by davisp** [comment]
Where's that custom domain setting? Had you asked I would've said to just add the CNAME file into your doc build somehow (ie, just check it into Git in the docs directory or what have you). But I should add a note to the README if there's a setting on GitHub now that gets out of whack with a push.

**Comment by allanstreib** [comment]
In Github website, in the repository "Settings" tab, there is a "Github Pages" section, which has a "Custom Domain" setting. I think this is somewhat new, and didn't realize it was just a front-end for the old CNAME file method.

**Comment by davisp** [comment]
There's now a command line option to write a CNAME file in 0.5.4.
