### ISSUE TITLE
ghp-import: error: Unknown Git error

### ISSUE THREAD

**Issue by kdheepak** [davisp/ghp-import#57]
I'm trying to run the following

```
$ ghp-import -m "Commit Message" -b gh-pages output
```

But I get the error message below

```
Usage: ghp-import [OPTIONS] DIRECTORY

ghp-import: error: Unknown Git error
```

I'm using 0.5.0

**Comment by ShaunaGordon** [comment]
I've run into the same issue and have confirmed that it's a new issue with 0.5.0. The project I'm using this in is making use of a requirements file, so I version-froze ghp-import to the previous version and the build was successful.

**Comment by davisp** [comment]
My bad. I took a commit for Windows compatibility without verifying that it didn't break things. I've fixed it and everything should be back to normal with 0.5.2.
