### ISSUE TITLE
ghp-import error on Windows 10 

### ISSUE THREAD

**Issue by sarwatfatimam** [davisp/ghp-import#59]
I am trying to run this command _ghp-import output -b master_to import everything in my output folder to master branch. However, I keep getting errors that says: 

_'ghp-import' is not recognized as an internal or external command, operable program or batch file._ 

 I have tried out solutions in previous posts but it is not working for me.

**Comment by davisp** [comment]
Likely its not on your path. Try either specifying the entire path to the command or adding the directory to whatever your PATH variable is on Windows.

**Comment by sarwatfatimam** [comment]
It did not work out. I finally upgraded the ghp-import from https://github.com/chevah/ghp-import/tree/win-support. Now, it's working.
