### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by jjsalomon** [davisp/ghp-import#61]
Hi im fairly new to using ghp-import, i'm trying to use it to import a file called "output" from dev branch to master branch and i keep getting this error.

Can anyone help ?

![image](https://cloud.githubusercontent.com/assets/9355058/22622145/df98f5d4-eb2a-11e6-8a47-e243fa84d84b.png)

**Comment by c-w** [comment]
I am unable to reproduce this issue on Windows 10 with conda 4.8.3 (see screenshot below) so I'll resolve this issue for now. Please feel free to re-open if you can provide more details on how to reproduce this. Thanks in advance!

![Screenshot of ghp-import run on Windows 10](https://user-images.githubusercontent.com/1086421/89107435-1c1ceb80-d3ff-11ea-9754-022752b5379f.png)
