### ISSUE TITLE
ImportError: cannot import name main

### ISSUE THREAD

**Issue by rabernat** [davisp/ghp-import#64]
I am trying to use ghp-import.

I installed via pip: `pip install ghp_import` which gave the output
```
Collecting ghp_import
Installing collected packages: ghp-import
Successfully installed ghp-import-0.5.5
```

When I try to run the `ghp-import` script, I get the error
```
Traceback (most recent call last):
  File "/Users/rpa/anaconda/bin/ghp-import", line 7, in <module>
    from ghp_import import main
ImportError: cannot import name main
```

Versions of stuff:
```
$ python --version
Python 2.7.11 :: Anaconda 4.0.0 (x86_64)
$ pip --version
pip 9.0.1 from /Users/rpa/anaconda/lib/python2.7/site-packages (python 2.7)
```

I feel silly to be stuck on this, but I really can't get it to work. I also tried cloning the repo and running setup.py, but I got the same error.

**Comment by davisp** [comment]
Strange. Can you check that ghp_import.py exists somewhere under `/Users/rpa/anaconda/lib/python2.7`? If it does, try running that with `python /path/to/ghp_import.py`.

Beyond that I've got nothing. Its been a long time since I've dealt with pypi/setup.py issues so nothing obvious strikes me with your setup.

**Comment by rabernat** [comment]
Yes, I can `import ghp_import` from python.

```python
>>> import ghp_import
>>> ghp_import?
Type:        module
String form: <module 'ghp_import' from '/Users/rpa/anaconda/lib/python2.7/site-packages/ghp_import/__init__.pyc'>
File:        ~/anaconda/lib/python2.7/site-packages/ghp_import/__init__.py
Docstring:   <no docstring>
```

However, there are no functions in it.
```python
>>> dir(ghp_import)
['__builtins__',
 '__doc__',
 '__file__',
 '__name__',
 '__package__',
 '__path__',
 '__version__']
```

**Comment by davisp** [comment]
Well that's odd. Can you find what else is in that directory? There's no __init__.py in ghp-import as its single file. There was a thing once with someone trying to make a windows thing but that never got merged if memory serves. I originally wrote this with the intention that people would just download a copy and vendor it so the whole install bits have just been tacked on by various contributors.

**Comment by rabernat** [comment]
The files in `/Users/rpa/anaconda/lib/python2.7/site-packages/ghp_import` are 
```
__init__.py
__init__.pyc
__main__.py
__main__.pyc
cli.py
cli.pyc
```

**Comment by rabernat** [comment]
Sorry, can you clarify what "vendor it" means? I am not familiar with this terminology.

**Comment by davisp** [comment]
Not sure what that cli.py is from, but I'm guessing you pulled in one of the forks somehow that's reshaped ghp-import for whatever reason.

By "vendor it" I just meant that I'd expected people to just check a copy into their source repository.

**Comment by rabernat** [comment]
> Not sure what that cli.py is from, but I'm guessing you pulled in one of the forks somehow that's reshaped ghp-import for whatever reason.

I just did `pip install ghp-import` (which is the same as `pip install ghp_import`). 
This just pulls the [latest version](https://pypi.python.org/pypi/ghp-import) from pypi. Is the pypi version one of these custom forks?

**Comment by c-w** [comment]
Closing this issue since it is 3 years old and was about Python 2 which is now EOL. @rabernat please reopen if you're still having issues with the latest ghp-import and Python versions.
