### ISSUE TITLE
Git author and committer environment variables are not respected

### ISSUE THREAD

**Issue by danielhoherd** [davisp/ghp-import#67]
The following [git environment variables](https://git-scm.com/book/gr/v2/Git-Internals-Environment-Variables) do not appear to be respected by ghp-import:

- GIT_AUTHOR_NAME
- GIT_AUTHOR_EMAIL
- GIT_COMMITTER_NAME
- GIT_COMMITTER_EMAIL

Probably more are not respected, but these are the ones I observed in my own environment after switching from ~/.gitconfig to environment variables. When I re-enabled these configurations in ~/.gitconfig and ran a test `ghp-import -p -r github -b gh-pages docs` the commit information was available in the new commit.

I attempted to run `ghp-import -s` but experienced the behaviors from #63.

This bug was originally [posted to mkdocs](https://github.com/mkdocs/mkdocs/issues/1383), but was found to be caused by ghp-import.

**Comment by c-w** [comment]
Hi @danielhoherd. A fix for this was just merged. Let me know if you have any additional questions, comments or concerns.

**Comment by danielhoherd** [comment]
I actually switched back to ~/.gitconfig because of this bug, but thanks for fixing it!

**Comment by c-w** [comment]
This has been released in [0.6.0](https://pypi.org/project/ghp-import/0.6.0/).
