### ISSUE TITLE
Option to preserve symlinks

### ISSUE THREAD

**Issue by dhimmel** [davisp/ghp-import#70]
Git [supports](https://stackoverflow.com/a/954575/4651668) symbolic links and symbolic links work with GitHub Pages ([see example](https://github.com/s4y/gh-pages-symlink-test)). 

Currently, the default behavior of ghp-import is to follow symlinks for files but not directories. Specifying `--follow-links` causes ghp-import to follow links for both files and directories: see https://github.com/davisp/ghp-import/issues/37#issuecomment-362861271. However, neither case preserves the symlinks, which is a feature that would help me with https://github.com/greenelab/manubot-rootstock/pull/101.

Perhaps the ideal behavior (disregarding backwards compatibility) would be to:

+ preserve symlinks that link to a file or directory within the "documentation directory"
+ follow symlinks that link to a file or directory outside of the "documentation directory"

However, given backwards compatibility, it would make sense perhaps to have a `--preserve-links` argument that would preserve all symbolic links. It would be mutually exclusive with `--follow-links`.

@davisp what do you think? I could try to take a crack at an implementation. I haven't looked much into how difficult this would be to implement.

**Comment by c-w** [comment]
@dhimmel Please submit a pull request for this. In the meantime, resolving this issue as it's over 2 years old. Feel free to reopen if it's still a blocker for you.
