### ISSUE TITLE
Is it possible to ignore certain files?

### ISSUE THREAD

**Issue by djhoese** [davisp/ghp-import#75]
I'm new to this project and am trying to find a way to have it ignore certain files and not upload them to the ghpages repository.  My use case is that I have a couple large files (images or other) that I use locally, create lower resolution/quality versions, and use those in my pages. The high resolution versions can stick around so they don't have to be regenerated, but I don't need them uploaded.

Is any functionality like this available? Any ideas for how this could be implemented? I'd be willing to try.

**Comment by kitagawa-hr** [comment]
@djhoese 
This works for me.

1. Add filter option
```py
def options():
    return [
        ...
        op.make_option('--filter', dest='filter', default=r'',
            help='Filter files you do not want to add. [%default]'),
]
```

2. Continue when fpath matches pattern
```py
def run_import(git, srcdir, opts):
    ...
        for fn in fnames:
            fpath = os.path.join(path, fn)
            fpath = normalize_path(fpath)
            if re.search(opts.filter, fpath):
                continue
            gpath = gitpath(os.path.relpath(fpath, start=srcdir))
            add_file(pipe, fpath, gpath)
```

```sh
$ ghp-import --filter="regex_you_dont_need_add" $(DIST_DIR)
```

https://github.com/kitagawa-hr/ghp-import/blob/feature/add_filter/ghp_import.py

**Comment by c-w** [comment]
Thanks @kitagawa-hr for submitting your solution. @djhoese @kitagawa-hr feel free to submit a pull request for this feature if you feel strongly about it. In the meantime, resolving this issue.
