### ISSUE TITLE
skip deploy if no update

### ISSUE THREAD

**Issue by casperdcl** [davisp/ghp-import#78]
Add an option e.g. `--if-changes` so that if the only thing which changes is the build timestamp comment in `index.html`, `mkdocs gh-deploy` should do nothing.

So far my workaround is:

```
mkdocs build
git fetch origin gh-pages:gh-pages
ghp-import site
[[ "$(git diff origin/gh-pages..gh-pages --numstat | grep -v sitemap.xml.gz)" != 1$'\t'1$'\t'index.html ]] \
  && git push -f origin gh-pages
```

this should fix #2

**Comment by c-w** [comment]
As discussed in #2, feel free to submit a pull request for this functionality, although using external git commands as in your submission looks like a great approach too.
